In this notebook, the progress of the Low-Rank Multiplication program is demonstrated. It involves two matrices, where SVD is performed on matrix A while matrix B remains unchanged. The percentage determines the number of vectors to retain from the sigma matrix, which are then used to multiply matrix A by matrix B.

In [3]:
import numpy as np

#First we are going to multiply matrix A and matrix B without either of them meing reduced by SVD
matrix_A = np.array([[1, 6, 4, 5], 
            [2, -1, 0, 2],
            [4, 3, -2, 3]]) 

matrix_B = np.array([[2, 5, 3, 2],
            [3, -2, 0, 5], 
            [1, 3, -3, 6]])

normal  = matrix_A @ matrix_B.T
print(normal)





[[54 16 37]
 [ 3 18 11]
 [23 21 37]]


In [4]:
def LRM(matrix_A, matrix_B, percentage):
 #Perform SVD on matrix A
    U, S, VT = np.linalg.svd(matrix_A)


    Sigma = np.diag(S)

    #Print all of the SVD matrices
    print("Matrix U:", U, sep="\n")
    print("Matrix Σ :", Sigma, sep="\n")
    print("Matrix V^T:", VT, sep="\n")  



matrix_A = np.array([[1, 6, 4, 5], 
            [2, -1, 0, 2],
            [4, 3, -2, 3]]) 

matrix_B = np.array([[2, 5, 3, 2],
            [3, -2, 0, 5], 
            [1, 3, -3, 6]])

LRM(matrix_A, matrix_B, 0.100)

Matrix U:
[[ 0.87319638  0.48205415 -0.07177664]
 [ 0.1219709  -0.35873414 -0.92543661]
 [ 0.47185928 -0.79933323  0.37204193]]
Matrix Σ :
[[9.72158252 0.         0.        ]
 [0.         5.04456835 0.        ]
 [0.         0.         2.24569887]]
Matrix V^T:
[[ 0.30906237  0.67198784  0.262207    0.61980666]
 [-0.68048381  0.16910452  0.69914466 -0.13979338]
 [-0.19347301  0.71732796 -0.45918463 -0.48698898]
 [-0.63560242 -0.07264028 -0.48124183  0.59928228]]
