<h1 style="color:pink;">Low Rank Multiplication Both Matrices</h1>
<p style="font-size:20px;">
In this notebook, we demonstrate the Low-Rank Multiplication algorithm applied to both matrices. Each matrix undergoes Singular Value Decomposition (SVD), and then they are multiplied together to observe how different percentage values affect the final results.
</p>

In [ ]:
import numpy as np 

def LRM_BOTH(matrix_A, matrix_B, percentage_A, percentage_B):
    #SVD decomposition of both matrices
    U_A, S_A, VT_A = np.linalg.svd(matrix_A, full_matrices=False)
    U_B, S_B, VT_B = np.linalg.svd(matrix_B, full_matrices=False)

    #Determine number of singular values to use in matrix S in both matrices
    num_singular_values_A = len(S_A)
    k_A = int(np.ceil(num_singular_values_A * (percentage_A / 100)))
    k_A = max(1, min(k_A, num_singular_values_A))

    num_singular_values_B = len(S_B)
    k_B = int(np.ceil(num_singular_values_B * (percentage_B / 100)))
    k_B = max(1, min(k_B, num_singular_values_B))

    #Keep only top-k components for each matrix 
    U_A_k = U_A[:, :k_A]
    S_A_k = np.diag(S_A[:k_A])
    VT_A_k = VT_A[:k_A, :]

    U_B_k = U_B[:, :k_B]
    S_B_k = np.diag(S_B[:k_B])
    VT_B_k = VT_B[:k_B, :]

    #Reconstruct low-rank approximations for both matrices
    A_reconstructed = U_A_k @ S_A_k @ VT_A_k
    B_reconstructed = U_B_k @ S_B_k @ VT_B_k

    print("\n--- Reconstructed (or approximated) Matrices ---")
    print("A_reconstructed:")
    print(A_reconstructed)
    print("\nB_reconstructed:")
    print(B_reconstructed)

    #Multiply reconstructed matrices 
    final_result = A_reconstructed @ B_reconstructed
    print("\n--- Final Multiplication Result ---")
    print(final_result)

    # Calculate percentage error between original and final multiplication after thye percentages 
    original_multiplication = matrix_A @ matrix_B
    error = np.linalg.norm(original_multiplication - final_result, 'fro') / np.linalg.norm(original_multiplication, 'fro') * 100
    print(f"\nPercentage Error between original and final multiplication: {error:.4f}%")

#Generate random test matrices
matrix_A = np.random.randint(-10, 11, size=(3, 4))  
matrix_B = np.random.randint(-10, 11, size=(4, 3))

print("Matrix A:")
print(matrix_A)
print("\nMatrix B:")
print(matrix_B)

print("\n--- Original Multiplication Result ---")
print(matrix_A @ matrix_B)

#Test function
LRM_BOTH(matrix_A, matrix_B, percentage_A=70, percentage_B=50)


Matrix A:
[[  6   4  -9   9]
 [  7   1   9   0]
 [ -1   9  -7 -10]]

Matrix B:
[[ -9  -6   8]
 [ -1  -7   2]
 [ 10   8   4]
 [  2 -10  -1]]

--- Original Multiplication Result ---
[[-130 -226   11]
 [  26   23   94]
 [ -90  -13   -8]]

--- Reconstructed (or approximated) Matrices ---
A_reconstructed:
[[ 6.00000000e+00  4.00000000e+00 -9.00000000e+00  9.00000000e+00]
 [ 7.00000000e+00  1.00000000e+00  9.00000000e+00  7.08476109e-16]
 [-1.00000000e+00  9.00000000e+00 -7.00000000e+00 -1.00000000e+01]]

B_reconstructed:
[[-10.77778309  -5.12265346   5.15489468]
 [ -2.48638319  -6.26646105  -0.37875854]
 [  6.72685193   9.61531806  -1.23823802]
 [  0.59787605  -9.30804348  -3.24391284]]

--- Final Multiplication Result ---
[[-129.77301424 -226.11201882   11.3632605 ]
 [ -17.3891975    44.41282731   24.56136204]
 [ -64.66638956  -25.5022876    32.54307305]]

Percentage Error between original and final multiplication: 33.3281%
