In this notebook, we can see the beginning of the low-rank multiplication algorithm. We perform SVD on matrix A and then multiply the U, Σ, and Vᵀ matrices by matrix B. It’s important to note that, in this notebook, we are not taking into consideration the rank to which we want to reduce the matrix.

The order of the multiplication is: final result = (U(Σ(Vᵀ(matrix_B))))

In [5]:
import numpy as np

# First we are going to multiply matrix A and matrix B without either of them being reduced by SVD

matrix_A = np.array([[1, 6, 4, 5],
                     [2, -1, 0, 2],
                     [4, 3, -2, 3]])

matrix_B = np.array([[2, 5, 3],
                     [3, -2, 0],
                     [1, 3, -3],
                     [2, 5, 6]])

# Direct matrix multiplication
direct_result = matrix_A @ matrix_B
print("Direct A @ B:", direct_result, sep="\n")

Direct A @ B:
[[34 30 21]
 [ 5 22 18]
 [21 23 36]]


In [14]:
import numpy as np

def LRM(matrix_A, matrix_B):
    # SVD decomposition
    U, S, VT = np.linalg.svd(matrix_A, full_matrices=False)
    Sigma = np.diag(S)

    print("Matrix U:", U, sep="\n")
    print("Matrix Σ:", Sigma, sep="\n")
    print("Matrix V^T:", VT, sep="\n")

    # Step 1: Multiply V^T and B first
    step1 = VT @ matrix_B  # (3x4) @ (4x3) -> (3x3)

    # Step 2: Scale each row of step1 by Sigma[i, i]
    total = np.zeros_like(step1)
    for i in range(Sigma.shape[0]):
        total[i, :] = Sigma[i, i] * step1[i, :]

    # Step 3: Multiply by U
    final_result = U @ total
    print("Final Result of LRM:", final_result, sep="\n")
    return final_result

final_result = LRM(matrix_A, matrix_B)


# Calculate percentage error
error_percentage = (np.linalg.norm(direct_result - final_result, 'fro') / np.linalg.norm(direct_result, 'fro')) * 100
print(f"Percentage Error between direct multiplication and LRM: {error_percentage:.6f}%")


Matrix U:
[[ 0.87319638  0.48205415 -0.07177664]
 [ 0.1219709  -0.35873414 -0.92543661]
 [ 0.47185928 -0.79933323  0.37204193]]
Matrix Σ:
[[9.72158252 0.         0.        ]
 [0.         5.04456835 0.        ]
 [0.         0.         2.24569887]]
Matrix V^T:
[[ 0.30906237  0.67198784  0.262207    0.61980666]
 [-0.68048381  0.16910452  0.69914466 -0.13979338]
 [-0.19347301  0.71732796 -0.45918463 -0.48698898]]
Final Result of LRM:
[[34. 30. 21.]
 [ 5. 22. 18.]
 [21. 23. 36.]]
Percentage Error between direct multiplication and LRM: 0.000000%
