<h1 style="color:pink;">Low Rank Multiplication Both Matrices</h1>
<p style="font-size:20px;">
In this notebook, we demonstrate the Low-Rank Multiplication algorithm applied to both matrices. Each matrix undergoes Singular Value Decomposition (SVD), and then they are multiplied together to observe how different percentage values affect the final results.
</p>

In [ ]:
import numpy as np 

def LRM_BOTH(matrix_A, matrix_B, percentage):
    # SVD decomposition of matrix A
    U_A, S_A, VT_A = np.linalg.svd(matrix_A, full_matrices=False)

    # SVD decomposition of matrix B
    U_B, S_B, VT_B = np.linalg.svd(matrix_B, full_matrices=False)

    #Print the results of the SVD for both matrices
    print("Matrix A - U:")
    print(U_A)
    print("Matrix B - U:")
    print(U_B)
    print("Matrix A - S:")
    print(S_A)
    print("Matrix B - S:")
    print(S_B)
    print("Matrix A - VT:")
    print(VT_A)
    print("Matrix B - VT:")
    print(VT_B)

    #return U_A, S_A, VT_A, U_B, S_B, VT_B


# Generate random test matrices
matrix_A = np.random.randint(-10, 11, size=(3, 4))  
matrix_B = np.random.randint(-10, 11, size=(4, 3))

print("Matrix A:")
print(matrix_A)
print("\nMatrix B:")
print(matrix_B)

# Test the function
LRM_BOTH(matrix_A, matrix_B, percentage=100)


Matrix A:
[[ 6 -7  0 -3]
 [ 6  3  1 -6]
 [10  7  8 -8]]

Matrix B:
[[  9   3  -1]
 [ -1  -5   7]
 [  9  -1   6]
 [  7 -10  -3]]
Matrix A - U:
[[ 0.1742103   0.97050077  0.16667041]
 [ 0.45730254  0.07016277 -0.8865391 ]
 [ 0.87208094 -0.23066305  0.43158939]]
Matrix B - U:
[[-0.42723795  0.64535921  0.0434123 ]
 [-0.14882587 -0.59617837 -0.56811185]
 [-0.60604564  0.17228988 -0.55013997]
 [-0.65423793 -0.44542008  0.61050005]]
Matrix A - S:
[18.86350743  9.38440996  3.01677595]
Matrix B - S:
[15.40981156 10.67765992  9.51447772]
Matrix A - VT:
[[ 0.66317923  0.33169876  0.39409161 -0.54301108]
 [ 0.41956296 -0.8735401  -0.18915857 -0.15847289]
 [-0.00109994 -0.26690231  0.85063526  0.45296976]]
Matrix B - VT:
[[-0.89101622  0.42900203 -0.14848353]
 [ 0.45300933  0.86150715 -0.22932068]
 [ 0.02954058 -0.27159287 -0.96195877]]
